In [ ]:
# para cambiar toda la columna a minusculas y sin tildes

import pandas as pd

# Supongamos que tienes un DataFrame llamado df y una columna "Nombre"
# Vamos a realizar las transformaciones en la columna "Nombre"

# Primero, convierte todos los valores de la columna a minúsculas
df["Nombre"] = df["Nombre"].str.lower()

# Luego, elimina las tildes de las vocales en la columna "Nombre"
df["Nombre"] = df["Nombre"].str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')

# Ahora, la columna "Nombre" tiene los valores en minúsculas y sin tildes

# Puedes imprimir el DataFrame para verificar los cambios
print(df)

In [ ]:
# para separar cada dataframe por comunidades :

import pandas as pd

# Supongamos que df es tu DataFrame original
# Y tienes una columna llamada "Comunidad Autonoma"

comunidades_autonomas = df["Comunidad Autonoma"].unique()

dataframes_por_comunidad = {}  # Un diccionario para almacenar DataFrames por comunidad

for comunidad in comunidades_autonomas:
    # Filtrar el DataFrame original por la comunidad actual
    comunidad_df = df[df["Comunidad Autonoma"] == comunidad]
    
    # Almacena el DataFrame de la comunidad en el diccionario
    dataframes_por_comunidad[comunidad] = comunidad_df

# Ahora, dataframes_por_comunidad contendrá DataFrames separados por comunidad autónoma
# Puedes acceder a un DataFrame específico por su comunidad autónoma
aragon_df = dataframes_por_comunidad["Aragon"]
madrid_df = dataframes_por_comunidad["Madrid"]

# Puedes hacer lo mismo para otras comunidades autónomas

In [ ]:
#PARA UNIR DATAFRAMES DE LAS COMUNIDADES

# Supongamos que tienes tres DataFrames: aragon_df, madrid_df y valencia_df

# Concatena los DataFrames en uno solo
dataframes = [aragon_df, madrid_df, valencia_df]
combined_df = pd.concat(dataframes, ignore_index=True)

# Ahora, combined_df contiene todos los datos de los tres DataFrames unidos en uno solo

# Puedes imprimir el resultado

In [ ]:
#PARA UNIR LOS DF POR COMUNIDAD Y DATOS 
# Supongamos que tienes tres DataFrames: paro_df, pib_df y poblacion_df

# Primero, une los DataFrames paro_df y pib_df por la columna "Comunidad Autonoma"
paro_pib_df = pd.merge(paro_df, pib_df, on="Comunidad Autonoma")

# Luego, une el DataFrame resultante con poblacion_df por la columna "Comunidad Autonoma"
final_df = pd.merge(paro_pib_df, poblacion_df, on="Comunidad Autonoma")

# Ahora, final_df contiene todos los datos unidos por comunidad autónoma

# Puedes imprimir el resultado
print(final_df)

In [3]:
import pandas as pd
# guarda en variables los datasets y su fuente
df_1 = pd.read_csv("data/incidencia_teletrabajo_comunidad.csv", sep=";")

In [29]:
# limpieza dataframe teletrabnajo
filtro = ((df_1['Teletrabajo'] == 'Personas que han teletrabajado') | (df_1['Teletrabajo'] == 'Total')) & (df_1['Clase de población'] == 'Total personas (16 a 74 años)')

personas_teletrabajo = df_1[filtro]
personas_teletrabajo.reset_index(drop=True, inplace=True)
personas_teletrabajo
filtro2 = personas_teletrabajo['Teletrabajo'] != 'Total'
personas_teletrabajo= personas_teletrabajo[filtro2]

personas_teletrabajo.reset_index(drop=True, inplace=True)
personas_teletrabajo.drop(0, inplace=True)
personas_teletrabajo.reset_index(drop=True, inplace=True)
personas_teletrabajo

,Clase de población,Total Nacional,Comunidades y Ciudades Autónomas,Teletrabajo,Total
0,Total personas (16 a 74 años),Total nacional,Andalucía,Personas que han teletrabajado,"6,2"
1,Total personas (16 a 74 años),Total nacional,Aragón,Personas que han teletrabajado,"7,3"
2,Total personas (16 a 74 años),Total nacional,"Asturias, Principado de",Personas que han teletrabajado,"5,7"
3,Total personas (16 a 74 años),Total nacional,"Balears, Illes",Personas que han teletrabajado,"4,5"
4,Total personas (16 a 74 años),Total nacional,Canarias,Personas que han teletrabajado,"7,0"
5,Total personas (16 a 74 años),Total nacional,Cantabria,Personas que han teletrabajado,"3,5"
6,Total personas (16 a 74 años),Total nacional,Castilla y León,Personas que han teletrabajado,"5,6"
7,Total personas (16 a 74 años),Total nacional,Castilla-La Mancha,Personas que han teletrabajado,"4,5"
8,Total personas (16 a 74 años),Total nacional,Cataluña,Personas que han teletrabajado,"13,4"
9,Total personas (16 a 74 años),Total nacional,Comunitat Valenciana,Personas que han teletrabajado,"7,7"
10,Total personas (16 a 74 años),Total nacional,Extremadura,Personas que han teletrabajado,"5,6"
11,Total personas (16 a 74 años),Total nacional,Galicia,Personas que han teletrabajado,"5,4"
12,Total personas (16 a 74 años),Total nacional,"Madrid, Comunidad de",Personas que han teletrabajado,"19,9"
13,Total personas (16 a 74 años),Total nacional,"Murcia, Región de",Personas que han teletrabajado,"5,5"
14,Total personas (16 a 74 años),Total nacional,"Navarra, Comunidad Foral de",Personas que han teletrabajado,"6,1"
15,Total personas (16 a 74 años),Total nacional,País Vasco,Personas que han teletrabajado,"7,2"
16,Total personas (16 a 74 años),Total nacional,"Rioja, La",Personas que han teletrabajado,"6,4"
17,Total personas (16 a 74 años),Total nacional,Ceuta,Personas que han teletrabajado,"2,3"
18,Total personas (16 a 74 años),Total nacional,Melilla,Personas que han teletrabajado,"3,5"