In [ ]:
# esto es una formula que encontre en internet por si necesitaba filtrar las columnas y ponerlas sin tildes y dodo en minusculas.
# no tuve que usarlo por que realmente me he basado en los datos numericos 

import pandas as pd

df["Nombre"] = df["Nombre"].str.lower()

df["Nombre"] = df["Nombre"].str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')

In [ ]:
# Ejemplo de como hacer una funcion para separar los dataframes por comunidades
# Al final he cambiado el enfoque y he hecho una tabla con los datos de todos los indices con sus valores, esto lo pense como otro enfoque

import pandas as pd

comunidades_autonomas = df["Comunidad Autonoma"].unique()

dataframes_por_comunidad = {}  

for comunidad in comunidades_autonomas:
        comunidad_df = df[df["Comunidad Autonoma"] == comunidad]
    
    
    dataframes_por_comunidad[comunidad] = comunidad_df

aragon_df = dataframes_por_comunidad["Aragon"]
madrid_df = dataframes_por_comunidad["Madrid"]

In [3]:
import pandas as pd
# guarda en variables los datasets y su fuente
df_1 = pd.read_csv("../Data/incidencia_teletrabajo_comunidad.csv", sep=";")

In [29]:
# limpieza dataframe teletrabnajo
filtro = ((df_1['Teletrabajo'] == 'Personas que han teletrabajado') | (df_1['Teletrabajo'] == 'Total')) & (df_1['Clase de población'] == 'Total personas (16 a 74 años)')

personas_teletrabajo = df_1[filtro]
personas_teletrabajo.reset_index(drop=True, inplace=True)
personas_teletrabajo
filtro2 = personas_teletrabajo['Teletrabajo'] != 'Total'
personas_teletrabajo= personas_teletrabajo[filtro2]

personas_teletrabajo.reset_index(drop=True, inplace=True)
personas_teletrabajo.drop(0, inplace=True)
personas_teletrabajo.reset_index(drop=True, inplace=True)
personas_teletrabajo

,Clase de población,Total Nacional,Comunidades y Ciudades Autónomas,Teletrabajo,Total
0,Total personas (16 a 74 años),Total nacional,Andalucía,Personas que han teletrabajado,"6,2"
1,Total personas (16 a 74 años),Total nacional,Aragón,Personas que han teletrabajado,"7,3"
2,Total personas (16 a 74 años),Total nacional,"Asturias, Principado de",Personas que han teletrabajado,"5,7"
3,Total personas (16 a 74 años),Total nacional,"Balears, Illes",Personas que han teletrabajado,"4,5"
4,Total personas (16 a 74 años),Total nacional,Canarias,Personas que han teletrabajado,"7,0"
5,Total personas (16 a 74 años),Total nacional,Cantabria,Personas que han teletrabajado,"3,5"
6,Total personas (16 a 74 años),Total nacional,Castilla y León,Personas que han teletrabajado,"5,6"
7,Total personas (16 a 74 años),Total nacional,Castilla-La Mancha,Personas que han teletrabajado,"4,5"
8,Total personas (16 a 74 años),Total nacional,Cataluña,Personas que han teletrabajado,"13,4"
9,Total personas (16 a 74 años),Total nacional,Comunitat Valenciana,Personas que han teletrabajado,"7,7"
10,Total personas (16 a 74 años),Total nacional,Extremadura,Personas que han teletrabajado,"5,6"
11,Total personas (16 a 74 años),Total nacional,Galicia,Personas que han teletrabajado,"5,4"
12,Total personas (16 a 74 años),Total nacional,"Madrid, Comunidad de",Personas que han teletrabajado,"19,9"
13,Total personas (16 a 74 años),Total nacional,"Murcia, Región de",Personas que han teletrabajado,"5,5"
14,Total personas (16 a 74 años),Total nacional,"Navarra, Comunidad Foral de",Personas que han teletrabajado,"6,1"
15,Total personas (16 a 74 años),Total nacional,País Vasco,Personas que han teletrabajado,"7,2"
16,Total personas (16 a 74 años),Total nacional,"Rioja, La",Personas que han teletrabajado,"6,4"
17,Total personas (16 a 74 años),Total nacional,Ceuta,Personas que han teletrabajado,"2,3"
18,Total personas (16 a 74 años),Total nacional,Melilla,Personas que han teletrabajado,"3,5"